# Generated by Django 4.2.8 on 2023-12-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productimage_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
